
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/minicrmdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mini-crm-network
    restart: unless-stopped


  db:
    image: mysql:9.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=minicrmdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mini-crm-network
    restart: unless-stopped


networks:
  mini-crm-network:
    name: mini-crm-network
    driver: bridge


volumes:
  mysql_data:
    name: mini-crm-mysql-data
